
#ROUTING website jeanForteroche
accueil:
    path: /
    controller: Host
    action: showHost
accueil2:
    path: /host
    controller: Host
    action: showHost
contact:
    path: /contact
    controller: Blog
    action: index
adminConnexion:
    path: /adminConnexion
    controller: Blog
    action: index
adminDashboard:
    path: /adminDashboard
    controller: Blog
    action: index
adminPost:
    path: /adminPost/:id
    controller: Blog
    action: index
billet:
    path: /billet/:id
    controller: Blog
    action: redirection
blog:
    path: /blog
    controller: Blog
    action: showBlog
legal:
    path: /legal
    controller: Blog
    action: index
contactPost:
    path: /contactPost/:id
    controller: Blog
    action: index
testBillet:
    path: /testBillet/:id
    controller: Billet
    action: showBillet