
#ROUTING website jeanForteroche
accueil:
    path: /
    controller: Host
    action: show
accueil2:
    path: /host
    controller: Host
    action: show
contact:
    path: /contact
    controller: Contact
    action: show
contactContact:
    path: /contactContact
    controller: Contact
    action: contact
signUpConnexion:
    path: /signUpConnexion
    controller: SignUpConnexion
    action: show
signSignUpConnexion:
    path: /signSignUpConnexion
    controller: SignUpConnexion
    action: sign
adminConnexion:
    path: /adminConnexion
    controller: AdminConnexion
    action: show
connectAdminConnexion:
    path: /connectAdminConnexion
    controller: AdminConnexion
    action: connect
disconnectAdminConnexion:
    path: /disconnectAdminConnexion
    controller: AdminConnexion
    action: disconnect
adminDashboard:
    path: /adminDashboard
    controller: AdminDashboard
    action: show
validAdminComment:
    path: /validAdminComment/:id
    controller: AdminComment
    action: valid
deleteAdminComment:
    path: /deleteAdminComment/:id
    controller: AdminComment
    action: delete
reportAdminComment:
    path: /reportAdminComment/:id
    controller: AdminComment
    action: report
virginAdminPost:
    path: /virginAdminPost
    controller: AdminPost
    action: showVirgin
adminPost:
    path: /adminPost/:id
    controller: AdminPost
    action: show
updateAdminPost:
    path: /updateAdminPost/:id
    controller: AdminPost
    action: update
createAdminPost:
    path: /createAdminPost
    controller: AdminPost
    action: create
deleteAdminPost:
    path: /deleteAdminPost/:id
    controller: AdminPost
    action: delete
billet:
    path: /billet/:id
    controller: Billet
    action: show
likeBillet:
    path: /likeBillet/:id
    controller: Billet
    action: like
blog:
    path: /blog
    controller: Blog
    action: show
legal:
    path: /legal
    controller: Legal
    action: show

