
#ROUTING website jeanForteroche
accueil:
    path: /
    controller: Host
    action: show
accueil2:
    path: /host
    controller: Host
    action: show
contact:
    path: /contact
    controller: Contact
    action: show
contactPost:
    path: /contact_post
    controller: Contact_Post
    action: post
adminConnexion:
    path: /adminConnexion
    controller: AdminConnexion
    action: show
adminDashboard:
    path: /adminDashboard
    controller: AdminDashboard
    action: show
adminPost:
    path: /adminPost/:id
    controller: Blog
    action: index
billet:
    path: /billet/:id
    controller: Billet
    action: show
blog:
    path: /blog
    controller: Blog
    action: show
legal:
    path: /legal
    controller: Legal
    action: show

