#contact:
#    path: /index.php/contact
#    controller: Blog
#    action: index
#    method: GET
#adminConnexion:
#    path: /index.php/adminConnexion
#    controller: Blog
#    action: index
#    method: GET
#billeterie:
#    path: /index.php/billet/:id
#    controller: Blog
#    action: index
#    method: GET
#test:
#    path: /index.php/test/:id
#    controller: Blog
#    action: index
#    method: GET
#ContactPost:
#    path: /index.php/contactPost/:id
#    controller: Blog
#    action: index
#    method: POST
#MODIF PATH_INFO

#ROUTING website jeanForteroche
accueil:
    path: /
    controller: Blog
    action: index
    method: GET
contact:
    path: /contact
    controller: Blog
    action: index
    method: GET
adminConnexion:
    path: /adminConnexion
    controller: Blog
    action: index
    method: GET
adminDashboard:
    path: /adminDashboard
    controller: Blog
    action: index
    method: GET
adminPost:
    path: /adminPost/:id
    controller: Blog
    action: index
    method: GET
billet:
    path: /billet/:id
    controller: Blog
    action: index
    method: GET
blog:
    path: /blog
    controller: Blog
    action: index
    method: GET
legal:
    path: /legal
    controller: Blog
    action: index
    method: GET
contactPost:
    path: /contactPost/:id
    controller: Blog
    action: index
    method: POST