
#ROUTING website jeanForteroche
accueil:
    path: /
    controller: Blog
    action: index
contact:
    path: /contact
    controller: Blog
    action: redirection
adminConnexion:
    path: /adminConnexion
    controller: Blog
    action: index
adminDashboard:
    path: /adminDashboard
    controller: Blog
    action: index
adminPost:
    path: /adminPost/:id
    controller: Blog
    action: index
billet:
    path: /billet/:id
    controller: Blog
    action: index
blog:
    path: /blog
    controller: Blog
    action: index
legal:
    path: /legal
    controller: Blog
    action: index
contactPost:
    path: /contactPost/:id
    controller: Blog
    action: index
